server.port=8081
spring.application.name=Numerosmotors
spring.datasource.url=jdbc:postgresql://localhost:5432/numerosdb
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

